name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # If 'configure' needs generation
    - name: Generate configure script
      run: autoconf 

    - name: Configure
      run: ./configure 

    - name: Build
      run: make

    - name: Test
      run: make check

    - name: Package
      run: make distcheck
